[project]
name = "agentdesk-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "alokKumarSingh89", email = "itsaloksingh2011@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "openai>=3.24.0",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.4",
    "tiktoken>=0.14.0",
]

[project.scripts]
agentdesk-ai = "agentdesk_ai:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
